package com.fourm.backend.model;

import javax.persistence.*;
import java.sql.Timestamp;
//@Entity is used to indicate that the class is an entity
//UserPerson is a class that is used to create a user
//UserPerson is not called User because User is a reserved word in Postgres
@Entity
public class UserPerson {
    // @Id
    // Id is the primary key and is auto generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    // name is the name of the user and is not unique
    @Column(name = "name")
    private String name;
    // registrationDate is the date the user registered and is not unique
    @Column(name = "registration_date")
    private Timestamp registrationDate;

    // email is the email of the user and is unique
    @Column(name = "email", unique = true)
    private String email;

    @Column(name = "password")
    private String password;

    //Role is the role of the user and is not unique
    //The role can be either admin or user
    @Column(name = "role")
    private String role = "user";

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public UserPerson() {

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Timestamp registrationDate) {
        this.registrationDate = registrationDate;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
