package com.fourm.backend.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.sql.Timestamp;
//@Entity is used to indicate that the class is an entity
//UserPerson is a class that is used to create a user
//UserPerson is not called User because User is a reserved word in Postgres
@Entity
public class UserPerson {
    // @Id
    // Id is the primary key and is auto generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    // name is the name of the user and is not unique
    private String name;
    // registrationDate is the date the user registered and is not unique
    private Timestamp registrationDate;

    public UserPerson() {

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Timestamp registrationDate) {
        this.registrationDate = registrationDate;
    }

}
